### ISSUE TITLE
Error running example

### ISSUE THREAD

**Issue by justinmchase** [ipfs/js-datastore-s3#1]
I'm getting this error when I try to run the example code:
```
Error: ENOENT: no such file or directory, open '/mnt/e/ipfs/.ipfs/repo.lock'
```
It in fact doesn't exist and I could create that folder and it probably would then work but my question is, should that file be going into s3? If not maybe it should create the folder. Since the repo folder is being created in s3 the disk folder is missing.

**Comment by jacobheun** [comment]
I think it would make sense for it to go on s3.  I created an issue in js-ipfs-repo to allow for creating custom lockers. In the interim you could use the memory locker to get the example working (I will update the example code):

```
const repo = new Repo('/tmp/test/.ipfs', {
  ...
  lock: 'memory'
})
```

**Comment by justinmchase** [comment]
Ok, thanks.

So what is the purpose of the lock file exactly? Also, if I had two ipfs instances running and both were pointed to the same bucket, would that be bad? It seems like if they have the same config/version then those files aren't a problem but in the blocks folder, are those files instance specific or are they deterministic and immutable? They idea here is it would be really easy to scale horizontally based on traffic if all of your instances were essentially sharing the same disk. But I'm not sure if that would work or not.

**Comment by jacobheun** [comment]
The lock file is currently setup to prevent multiple nodes from using a single repo, so it would be against the current design to do that. I'm not sure if there are any plans to change that in the future as I'm still relatively new to the project.

Blocks are deterministic. In theory multiple nodes would be able to access the information just fine, but I am not sure what other side effects you'd encounter. S3 doesn't allow concurrent writes to the same object and the last write wins. Since the block path is based on its hashed content, as long as the written content is not malformed it shouldn't matter, in theory.

**Comment by justinmchase** [comment]
Thanks, that is what I was assuming was true also. It helps to have a little confirmation. I think I'm going to try to run multiple nodes with the same repo and see what happens :) If there are a few small issues I'll make PR's but if I find out there are big problems I'll find a different approach. But it could be a dramatic simplification to have 1 repo.
